In [1]:
import pandas as pd
pd.set_option('display.max_colwidth', -1) #full colunm dispaly

result=pd.read_csv("Image-Classification-and-Price-prediction/scrapping/data/lekmer.csv", encoding='utf-8',index_col=False)
print(result.count())
result.head(3)

name          31110
brand         31110
gender        31110
category      31110
size          31110
price         31110
url           31110
img_url       31110
article_no    31110
blob_url      31110
dtype: int64

,name,brand,gender,category,size,price,url,img_url,article_no,blob_url
0,\nRyggsäck Grön Camo\n,\nNew York Yankees\n,unisex,accessories,\n6 - 16 år\n,199 kr,https://lekmer.se/ryggsack-gron-camo/p/130925,https://lekmer.se/images/405205/full.jpg,465903,https://storage.googleapis.com/urbankiddo/lekmer/465903
1,\nRyggsäck Grön Camo\n,\nNew York Yankees\n,unisex,accessories,\n6 - 16 år\n,199 kr,https://lekmer.se/ryggsack-gron-camo/p/130925,https://lekmer.se/images/405205/full.jpg,465903,https://storage.googleapis.com/urbankiddo/lekmer/465903
2,\nStickad Mössa med Öron Grå\n,\nGap\n,unisex,accessories,\n0-3 mån\n,145 kr,https://lekmer.se/stickad-mossa-med-oron-gra/p/140335,https://lekmer.se/images/404894/full.jpg,536873,https://storage.googleapis.com/urbankiddo/lekmer/536873

In [2]:
df=result.drop_duplicates()
result.drop_duplicates().count()

name          11657
brand         11657
gender        11657
category      11657
size          11657
price         11657
url           11657
img_url       11657
article_no    11657
blob_url      11657
dtype: int64

In [3]:
df['price'].unique()

array(['199 kr', '145 kr', '309 kr', '69 kr', '435 kr', '365 kr',
       '139 kr', '179 kr', '229 kr', '315 kr', '265 kr', '249 kr',
       '289 kr', '189 kr', '149 kr', '79 kr', '299 kr', '169 kr',
       '119 kr', '325 kr', '129 kr', '349 kr', '175 kr', '99 kr',
       '209 kr', '509 kr', '439 kr', '399 kr', '75 kr', '699 kr',
       '799 kr', '239 kr', '159 kr', '359 kr', '279 kr', '195 kr',
       '379 kr', '200 kr', '329 kr', '335 kr', '295 kr', '115 kr',
       '245 kr', '250 kr', '269 kr', '109 kr', '549 kr', '499 kr',
       '219 kr', '255 kr', '319 kr', '185 kr', '155 kr', '165 kr',
       '125 kr', '305 kr', '395 kr', '575 kr', '449 kr', '259 kr',
       '235 kr', '529 kr', '455 kr', '475 kr', '425 kr', '225 kr',
       '385 kr', '369 kr', '419 kr', '479 kr', '350 kr', '285 kr',
       '415 kr', '459 kr', '565 kr', '429 kr', '345 kr', '469 kr',
       '420 kr', '519 kr', '389 kr', '105 kr', '339 kr', '275 kr',
       '135 kr', '205 kr', '470 kr', '539 kr', '599 kr', '895 kr',
       '409 kr', '89 kr', '849 kr', '999 kr', '649 kr', '819 kr',
       '489 kr', '375 kr', '215 kr', '445 kr', '355 kr', '505 kr',
       '579 kr', '629 kr', '405 kr', '559 kr', '569 kr', '485 kr',
       '555 kr', '749 kr', '679 kr', '465 kr', '480 kr', '450 kr',
       '400 kr', '685 kr', '490 kr', '639 kr', '300 kr', '525 kr',
       '995 kr', '899 kr', '1045 kr', '939 kr', '500 kr', '95 kr',
       '540 kr', '590 kr', '495 kr', '645 kr', '401 kr', '675 kr',
       '669 kr', '625 kr', '344 kr', '298 kr', '321 kr', '330 kr',
       '560 kr', '785 kr', '1399 kr', '1499 kr', '1299 kr', '1099 kr',
       '515 kr', '745 kr', '1189 kr', '839 kr', '595 kr', '605 kr',
       '845 kr', '535 kr', '909 kr', '1469 kr', '619 kr', '1195 kr',
       '1199 kr', '1079 kr', '1119 kr', '959 kr', '719 kr', '1395 kr',
       '769 kr', '815 kr', '859 kr', '1249 kr', '729 kr', '190 kr',
       '85 kr', '59 kr', '55 kr', '80 kr', '130 kr', '150 kr', '49 kr',
       '550 kr', '705 kr', '615 kr', '650 kr', '735 kr', '789 kr',
       '1105 kr', '860 kr', '985 kr', '589 kr', '889 kr', '1699 kr',
       '659 kr', '1095 kr', '1899 kr', '609 kr', '1459 kr', '1359 kr',
       '715 kr', '950 kr', '779 kr', '969 kr', '929 kr', '2199 kr',
       '585 kr', '687 kr', '458 kr', '1999 kr', '1599 kr', '1799 kr',
       '270 kr', '220 kr', '810 kr', '280 kr', '240 kr', '572 kr',
       '180 kr', '260 kr', '665 kr', '230 kr', '154 kr', '545 kr',
       '1679 kr', '184 kr', '410 kr', '630 kr', '380 kr', '750 kr',
       '850 kr', '600 kr', '949 kr', '1049 kr', '1159 kr', '1149 kr',
       '865 kr', '935 kr', '310 kr', '1000 kr', '915 kr', '635 kr',
       '1055 kr', '709 kr', '1029 kr'], dtype=object)

In [4]:
df2=df
df2['price']=df2['price'].str.replace(' kr','')
df2['price']=df2['price'].astype(float)
df2['price']=df2['price'].round()
df2['price']=df2['price'].astype(int)

df2['price'].unique()

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

array([ 199,  145,  309,   69,  435,  365,  139,  179,  229,  315,  265,
        249,  289,  189,  149,   79,  299,  169,  119,  325,  129,  349,
        175,   99,  209,  509,  439,  399,   75,  699,  799,  239,  159,
        359,  279,  195,  379,  200,  329,  335,  295,  115,  245,  250,
        269,  109,  549,  499,  219,  255,  319,  185,  155,  165,  125,
        305,  395,  575,  449,  259,  235,  529,  455,  475,  425,  225,
        385,  369,  419,  479,  350,  285,  415,  459,  565,  429,  345,
        469,  420,  519,  389,  105,  339,  275,  135,  205,  470,  539,
        599,  895,  409,   89,  849,  999,  649,  819,  489,  375,  215,
        445,  355,  505,  579,  629,  405,  559,  569,  485,  555,  749,
        679,  465,  480,  450,  400,  685,  490,  639,  300,  525,  995,
        899, 1045,  939,  500,   95,  540,  590,  495,  645,  401,  675,
        669,  625,  344,  298,  321,  330,  560,  785, 1399, 1499, 1299,
       1099,  515,  745, 1189,  839,  595,  605,  845,  535,  909, 1469,
        619, 1195, 1199, 1079, 1119,  959,  719, 1395,  769,  815,  859,
       1249,  729,  190,   85,   59,   55,   80,  130,  150,   49,  550,
        705,  615,  650,  735,  789, 1105,  860,  985,  589,  889, 1699,
        659, 1095, 1899,  609, 1459, 1359,  715,  950,  779,  969,  929,
       2199,  585,  687,  458, 1999, 1599, 1799,  270,  220,  810,  280,
        240,  572,  180,  260,  665,  230,  154,  545, 1679,  184,  410,
        630,  380,  750,  850,  600,  949, 1049, 1159, 1149,  865,  935,
        310, 1000,  915,  635, 1055,  709, 1029])

In [25]:
df['size'].unique()

array(['6-16Y', '0-3M', 'S/M', '52', 'T1', '6Y', '2-3Y', '48/50', '1-2Y',
       '6M', 'OneSize', '46/48', '6-12M', '0-6M', 'XS/S', '42/44',
       'Strl1', '0', '1-4Y', '48', '36', '2', '0,5', '49', '74/80',
       '2-6Y', '47', '45', '62/68', '50/56', '3', '8', '1', '3-9M', '37',
       '44', '5', '4-10M', 'Baby', '38/40', '10M-2Y', '12-18M', 'XL',
       '46', '50', '122/128', '98/104', '41/45', 'OneSize1-3Y', '3-5Y',
       '41', '56', 'XXS', '44/46', '134/140', '68/74', '0-6m', 'XS', 'S',
       '0-12M', '4-5Y', '0-1Y', '1-3Y', 'Mini', 'L/XL', '3-6M', '54',
       '110/128', '3-7Y', '8-12Y', 'M-L', '51', '55', '0-2Y', '50/52',
       '54/56', 'M', '53', '58', 'L', '0-4M', '40/42', '36/38', '4SR',
       '52/54', 'Premature', '12', '13', '4-6Y', '86/92', '70', '46/47',
       'NB', '70-80', '34', '6', '34/36', '70/80', '90', '60', '4',
       '56/60', 'JR', '68', '40CM', '40', '4/6-8y', '40/44', 'BABY',
       'Gul', 'Baby0-3Y', 'Blå', '24-25EU', '19', '21', '146/152',
       '110/116', '80', '92', '3Y', '12M', '30-31EU', '20-21EU', '33',
       '30', '24', '20', '100', '80/90', '140/150', '3-4Y', '98', '104',
       '110', '62', '2Y', '32EU', '80/86', '18-24M', '4Y', '5Y',
       '21-22EU', '116', '74', '86', '98-104', '11-12Y', '14Y', '12Y',
       '6-9kg', '9-12kg', '3+Y', '9-12M', '6-9M', '0-3Y', '12-13Y',
       '5-6Y', '8Y', '28EU', '3-6kg', '12-18kg', '120', '3m/62', '4y/104',
       '18m/86', '2y/92', '9m/74', '12m/80', '1M', '3M', 'Nyfödd', '9M',
       '18M', 'Newborn', '56/62', '92/98', '44/48', '92/104', '122',
       '74-80', '62-68', '6y/116', '1year', '128', '7Y', '6-7Y', '24M',
       'XXL', '10-11Y', '16Y', '8-9Y', '1Y', '10-12Y', '2-4yrs', '36M',
       '140', '7-8Y', '6m/68', '9y/134', '9-10Y', '14', '7', '146', '164',
       '104/110', '134', '13-14Y', '10Y', '8-10Y', '152', '13-15Y', '160',
       '5y/110', '23EU', '21EU', '25EU', '22EU', '25-26EU', '27EU',
       '31EU', '29EU', '20EU', '25', 'C10', '30EU', 'J1', '24EU', '22',
       '26EU', '22-23EU', '19EU', 'J2', '28', 'C7', '31', '27', '36EU',
       '33EU', 'J3', 'C6', '33-34EU', '98/110', '110-116', '34-38',
       '15-16Y', '17', '23', '26-27EU', '12-24M', '15-16', '37-39',
       '16-18', '19-21', '23-26', '23-24', '68-74', '0-6mdr', '17-19',
       '28-30', '23-31', 'UK13-2', '27-30', '56-62', '35-39', '31-34',
       '150', 'XL/XXL', 'M/L', '74/86', '38-41', '22-24', '15-18',
       '20-22', 'UK3-5', '35', '35-38', '38-42', '23-30', '28/30',
       '13-14', '15/18', '13/14', '19/22', '23/26', 'C4', 'YMD',
       '19-20EU', 'YXS', '130', '3y/98', '158/164', '116/122', 'Svart',
       'ONESIZE', 'C5', '16', '21.5', '28.5', '27-29', '27/28', '18EU',
       '23.5', '32.5', '32', '20-21', '26', '34EU', '35EU', '29/30',
       '25/26', '33/34', '17EU', '27-28EU', '24-36M/24-25', '6-12M/20-21',
       '16-17', '0-6M/16-19', '29', '24.5', '18', '24-25', '38', '27.5',
       '35.5', '31.5', '36.5', '38.5', '33-34', 'C2-3', '19/20', '39',
       '31/32', 'C4/5', '17-18', '18-19', '41/42', '39/40', '0/1',
       'M2/W4', 'US4', '17/18', '15', '25-26', '38EU', '18.5', 'C13',
       '13US', 'C4/C5', '17-18EU', 'US13', 'US11'], dtype=object)

In [27]:
df[df['size']=='C4/5']

,name,brand,gender,category,size,price,url,img_url,article_no,blob_url
22754,\nCrocband Kids Neon Magenta/Neon Purple\n,\nCrocs\n,unisex,shoes,C4/5,349,https://lekmer.se/crocband-kids-neon-magenta-neon-purple/p/86395,https://lekmer.se/images/266114/full.jpg,139874,https://storage.googleapis.com/urbankiddo/lekmer/139874
23146,\nClassic Kids Ocean\n,\nCrocs\n,unisex,shoes,C4/5,249,https://lekmer.se/classic-kids-ocean/p/15335,https://lekmer.se/images/269681/full.jpg,153156,https://storage.googleapis.com/urbankiddo/lekmer/153156
23188,\nClassic Kids Navy\n,\nCrocs\n,unisex,shoes,C4/5,249,https://lekmer.se/classic-kids-navy/p/43057,https://lekmer.se/images/393616/full.jpg,178968,https://storage.googleapis.com/urbankiddo/lekmer/178968

In [6]:
df3=df2
df3['size']=df3['size'].str.strip()
df3['size']=df3['size'].str.replace(' ','')
df3['size']=df3['size'].str.replace('år','Y')
df3['size']=df3['size'].str.replace('years','Y')
df3['size']=df3['size'].str.replace('mån','M')
df3['size']=df3['size'].str.replace('Years','Y')
df3['size']=df3['size'].str.replace('months','M')
df3['size']=df3['size'].str.replace('Months','M')

df3['size']=df3['size'].str.replace('month','M')
df3['size']=df3['size'].str.replace('Mader','M')
df3['size']=df3['size'].str.split('(').str.get(0)
df3['size']=df3['size'].str.split('\n').str.get(0)

df3['size']=df3['size'].str.replace('cm','')


# df3['size'].unique()

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()
/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':
/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]
/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  app.launch_new_instance()

In [32]:
sz_list=df3['size'].tolist()

new_sz=[]
for s in sz_list:
    if s.find("m")!=-1:
        s=s.split('m')[0]+'M'
    if s.find("year")!=-1:
        s=s.replace("year","Y")
    if s.find("yrs")!=-1:
        s=s.replace("yrs","Y")
    if s.find("y")!=-1:
        s=s.replace("y","Y")
    if s in ['4/6-8Y','4Y/104','5Y/110','6-12M/20-21','6Y/116','9Y/134', '3Y/98', '0-6M/16-19']:
        s=s.replace("4/6-8Y","6-8Y")
        s=s.replace('3Y/98',"3Y")
        s=s.replace('0-6M/16-19',"0-6M")

        s=s.replace("4Y/104","4Y")
        s=s.replace("5Y/110","5Y")
        s=s.replace("6-12M/20-21","6-12M")
        s=s.replace("6Y/116","6Y")
        s=s.replace("9Y/134","9Y")
    s=s.replace("'BabY0-3Y'","0-3Y")      
    s=s.replace('24-36M/24-25',"24-36M") 
    
    s=s.replace('OneSize1-3Y',"One Size")
    s=s.replace('PreM',"Premature")
    s=s.replace('CM',"")
    
    
    if s in ['BABY', 'BabY' 'Gul', 'J1', 'J2', 'J3', 'JR','M2/W4', 'Mini', 'NB', 'NYfödd','T1','YMD','YXS',
            'BabY', 'BabY0-3Y', 'Blå', 'Gul','Newborn', 'ONESIZE', 'One Size', 'OneSize', 'Premature','Strl1', 'Svart',
             'UK13-2', 'UK3-5', 'US11', 'US13', 'US4',
            'C10', 'C13', 'C2-3', 'C4', 'C4/5', 'C4/C5', 'C5', 'C6', 'C7',]:
        s='Na'

    s=s.replace(',',"-")
    s=s.replace('/',"-")

    new_sz.append(s)
set(new_sz)

{'0',
 '0-1',
 '0-12M',
 '0-1Y',
 '0-2Y',
 '0-3M',
 '0-3Y',
 '0-4M',
 '0-5',
 '0-6M',
 '1',
 '1-2Y',
 '1-3Y',
 '1-4Y',
 '10-11Y',
 '10-12Y',
 '100',
 '104',
 '104-110',
 '10M-2Y',
 '10Y',
 '11-12Y',
 '110',
 '110-116',
 '110-128',
 '116',
 '116-122',
 '12',
 '12-13Y',
 '12-18M',
 '12-18kg',
 '12-24M',
 '120',
 '122',
 '122-128',
 '128',
 '12M',
 '12Y',
 '13',
 '13-14',
 '13-14Y',
 '13-15Y',
 '130',
 '134',
 '134-140',
 '13US',
 '14',
 '140',
 '140-150',
 '146',
 '146-152',
 '14Y',
 '15',
 '15-16',
 '15-16Y',
 '15-18',
 '150',
 '152',
 '158-164',
 '16',
 '16-17',
 '16-18',
 '160',
 '164',
 '16Y',
 '17',
 '17-18',
 '17-18EU',
 '17-19',
 '17EU',
 '18',
 '18-19',
 '18-24M',
 '18.5',
 '18EU',
 '18M',
 '19',
 '19-20',
 '19-20EU',
 '19-21',
 '19-22',
 '19EU',
 '1M',
 '1Y',
 '2',
 '2-3Y',
 '2-4Y',
 '2-6Y',
 '20',
 '20-21',
 '20-21EU',
 '20-22',
 '20EU',
 '21',
 '21-22EU',
 '21.5',
 '21EU',
 '22',
 '22-23EU',
 '22-24',
 '22EU',
 '23',
 '23-24',
 '23-26',
 '23-30',
 '23-31',
 '23.5',
 '23EU',
 '24',
 '24-25',
 '24-25EU',
 '24-36M',
 '24.5',
 '24EU',
 '24M',
 '25',
 '25-26',
 '25-26EU',
 '25EU',
 '26',
 '26-27EU',
 '26EU',
 '27',
 '27-28',
 '27-28EU',
 '27-29',
 '27-30',
 '27.5',
 '27EU',
 '28',
 '28-30',
 '28.5',
 '28EU',
 '29',
 '29-30',
 '29EU',
 '2Y',
 '2Y-92',
 '3',
 '3+Y',
 '3-4Y',
 '3-5Y',
 '3-6M',
 '3-6kg',
 '3-7Y',
 '3-9M',
 '30',
 '30-31EU',
 '30EU',
 '31',
 '31-32',
 '31-34',
 '31.5',
 '31EU',
 '32',
 '32.5',
 '32EU',
 '33',
 '33-34',
 '33-34EU',
 '33EU',
 '34',
 '34-36',
 '34-38',
 '34EU',
 '35',
 '35-38',
 '35-39',
 '35.5',
 '35EU',
 '36',
 '36-38',
 '36.5',
 '36EU',
 '36M',
 '37',
 '37-39',
 '38',
 '38-40',
 '38-41',
 '38-42',
 '38.5',
 '38EU',
 '39',
 '39-40',
 '3M',
 '3Y',
 '4',
 '4-10M',
 '4-5Y',
 '4-6Y',
 '40',
 '40-42',
 '40-44',
 '41',
 '41-42',
 '41-45',
 '42-44',
 '44',
 '44-46',
 '44-48',
 '45',
 '46',
 '46-47',
 '46-48',
 '47',
 '48',
 '48-50',
 '49',
 '4SR',
 '4Y',
 '5',
 '5-6Y',
 '50',
 '50-52',
 '50-56',
 '51',
 '52',
 '52-54',
 '53',
 '54',
 '54-56',
 '55',
 '56',
 '56-60',
 '56-62',
 '58',
 '5Y',
 '6',
 '6-12M',
 '6-16Y',
 '6-7Y',
 '6-8Y',
 '6-9M',
 '6-9kg',
 '60',
 '62',
 '62-68',
 '68',
 '68-74',
 '6M',
 '6Y',
 '7',
 '7-8Y',
 '70',
 '70-80',
 '74',
 '74-80',
 '74-86',
 '7Y',
 '8',
 '8-10Y',
 '8-12Y',
 '8-9Y',
 '80',
 '80-86',
 '80-90',
 '86',
 '86-92',
 '8Y',
 '9-10Y',
 '9-12M',
 '9-12kg',
 '90',
 '92',
 '92-104',
 '92-98',
 '98',
 '98-104',
 '98-110',
 '9M',
 '9Y',
 'L',
 'L-XL',
 'M',
 'M-L',
 'Na',
 'S',
 'S-M',
 'XL',
 'XL-XXL',
 'XS',
 'XS-S',
 'XXL',
 'XXS'}

In [16]:
'35Y-62'.replace("5Y","M")

'3M-62'

In [33]:
df3['new_size']=new_sz

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [35]:
df3['brand']=df3['brand'].str.strip()

df3['brand'].unique()

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

array(['New York Yankees', 'Gap', 'My Little Pony', 'Timberland',
       'Kuling', 'Minymo', 'The North Face', 'Emma och Malena', 'Hummel',
       'Mini A Ture', 'Mumin', 'ebbe Kids', 'Pippi Långstrump',
       'Didriksons', 'Frugi', 'Reima', 'Ticket To Heaven', 'Small Rags',
       'Geggamoja', 'Melton', 'Fixoni', 'One We Like', 'Joha', 'Retour',
       'Isbjörn Of Sweden', 'Joules', 'Cebe', 'Bergans', 'LEGO Wear',
       'Mikk-Line', 'Lindberg', 'Levis Kids', 'The BRAND',
       'Elodie Details', 'Hatley', 'Name It', 'Jocko', 'Little Jalo',
       'A Happy Brand', 'Disney Minnie Mouse', "Lands' End",
       'Marvel Spider-Man', 'Disney Frozen', 'Tenson', 'Snapper Rock',
       'Nova Star', 'UGG', 'Skip Hop', 'Paw Patrol', 'Igor', 'Toms',
       'Småfolk', 'Disney Pixar Cars', 'Disney Mickey Mouse',
       'Max Collection', 'Champion', 'EnFant', 'iPLAY', 'Swimpy',
       'Zunblock', 'The Tiny Universe', 'Gardner and the gang',
       'Smiling Shark', 'Hust&Claire;', "Carter's", 'Salto', 'Creamie',
       'A Denim Story', 'OshKosh', 'Filemon Kid',
       'Emma och Malena Maternity', 'Puma', 'Manchester United',
       'Barcelona FC', 'Hello Kitty', 'PJ Masks', 'Superman', 'Batman',
       'Converse', 'Play', 'Under Armour', 'Tretorn', 'Celavi', 'Viking',
       'Crocs', 'Bisgaard', 'Vossatassar', 'Emoji', 'LEGO NINJAGO',
       'Nalle Puh', 'Disney Bambi', 'Disney Princess', 'Fireman Sam',
       'Super Mario', 'Brandman Sam', 'Peanuts', 'The Avengers',
       'Star Wars', 'L.O.L', 'Lego', 'Minecraft', 'Geox',
       'Emil i Lönneberga', 'Vans', 'Me Too', 'Max Collection Christmas',
       'ECCO', 'Gulliver', 'By Nils', 'Naturino', 'Dr. Martens',
       'Superfit', 'Havaianas', 'Shepherd', 'Sorel', 'Emu Australia',
       'Bobux', 'SPROX', 'Junior League'], dtype=object)

In [36]:
colunms=['article_no','gender','category','price','new_size','brand']
df4=df3[colunms]
df4.head(2)

  article_no  gender     category  price new_size             brand
0  465903     unisex  accessories  199    6-16Y    New York Yankees
2  536873     unisex  accessories  145    0-3M     Gap

In [ ]:
df

In [37]:
dfr=df4
dfr.to_csv('lekmer_cleaned.csv',index=False) #for rows not showing