In [45]:
import pandas as pd
result=pd.read_csv("zara.csv", encoding='utf-8',index_col=False)
print(result.count())
result.head()

name           13282
brand          13282
gender         13282
category       13282
size           11010
price          13282
composition    13280
color          13282
url            13282
img_url        13282
article_no     13282
blob_url       13282
dtype: int64

,name,brand,gender,category,size,price,composition,color,url,img_url,article_no,blob_url
0,DENIMJACKA,zara,boy,YTTERJACKOR,116,"299,00 SEK",100% BOMULL,Rödorange,https://www.zara.com/se/sv/denimjacka-p06987755.html,https://static.zara.net/photos///2019/I/0/3/p/6987/755/670/8/w/560/6987755670_2_10_1.jpg?ts=1562665297495,23422850,https://storage.googleapis.com/urbankiddo/zara/23422850
1,DENIMJACKA,zara,boy,YTTERJACKOR,122,"299,00 SEK",100% BOMULL,Rödorange,https://www.zara.com/se/sv/denimjacka-p06987755.html,https://static.zara.net/photos///2019/I/0/3/p/6987/755/670/8/w/560/6987755670_2_10_1.jpg?ts=1562665297495,23422850,https://storage.googleapis.com/urbankiddo/zara/23422850
2,DENIMJACKA,zara,boy,YTTERJACKOR,128,"299,00 SEK",100% BOMULL,Rödorange,https://www.zara.com/se/sv/denimjacka-p06987755.html,https://static.zara.net/photos///2019/I/0/3/p/6987/755/670/8/w/560/6987755670_2_10_1.jpg?ts=1562665297495,23422850,https://storage.googleapis.com/urbankiddo/zara/23422850
3,DENIMJACKA,zara,boy,YTTERJACKOR,134,"299,00 SEK",100% BOMULL,Rödorange,https://www.zara.com/se/sv/denimjacka-p06987755.html,https://static.zara.net/photos///2019/I/0/3/p/6987/755/670/8/w/560/6987755670_2_10_1.jpg?ts=1562665297495,23422850,https://storage.googleapis.com/urbankiddo/zara/23422850
4,DENIMJACKA,zara,boy,YTTERJACKOR,140,"299,00 SEK",100% BOMULL,Rödorange,https://www.zara.com/se/sv/denimjacka-p06987755.html,https://static.zara.net/photos///2019/I/0/3/p/6987/755/670/8/w/560/6987755670_2_10_1.jpg?ts=1562665297495,23422850,https://storage.googleapis.com/urbankiddo/zara/23422850

In [46]:
len(result['article_no'].unique())

1528

In [47]:
result.groupby('article_no').count()

,name,brand,gender,category,size,price,composition,color,url,img_url,blob_url
article_no,,,,,,,,,,,
7885549,5,5,5,5,5,5,5,5,5,5,5
7885902,8,8,8,8,8,8,8,8,8,8,8
7886479,8,8,8,8,8,8,8,8,8,8,8
7886480,8,8,8,8,8,8,8,8,8,8,8
7886496,8,8,8,8,8,8,8,8,8,8,8
7886877,8,8,8,8,8,8,8,8,8,8,8
7886878,8,8,8,8,8,8,8,8,8,8,8
7887282,8,8,8,8,8,8,8,8,8,8,8
7887323,12,12,12,12,12,12,12,12,12,12,12
7887389,8,8,8,8,8,8,8,8,8,8,8
7887390,8,8,8,8,8,8,8,8,8,8,8
7887391,8,8,8,8,8,8,8,8,8,8,8
7887648,8,8,8,8,8,8,8,8,8,8,8
7887649,8,8,8,8,8,8,8,8,8,8,8
7887932,8,8,8,8,8,8,8,8,8,8,8
7888108,7,7,7,7,7,7,7,7,7,7,7
7888181,5,5,5,5,5,5,5,5,5,5,5
7888405,8,8,8,8,8,8,8,8,8,8,8
7888581,5,5,5,5,5,5,5,5,5,5,5
7888618,8,8,8,8,8,8,8,8,8,8,8
7888619,8,8,8,8,8,8,8,8,8,8,8
7888620,8,8,8,8,8,8,8,8,8,8,8
7888696,5,5,5,5,5,5,5,5,5,5,5
7916560,5,5,5,5,5,5,5,5,5,5,5
7916602,6,6,6,6,6,6,6,6,6,6,6
7929507,8,8,8,8,8,8,8,8,8,8,8
7929543,5,5,5,5,5,5,5,5,5,5,5
7929617,8,8,8,8,8,8,8,8,8,8,8
7929618,8,8,8,8,8,8,8,8,8,8,8
7929624,6,6,6,6,6,6,6,6,6,6,6
...,...,...,...,...,...,...,...,...,...,...,...
23906343,8,8,8,8,8,8,8,8,8,8,8
23906345,8,8,8,8,8,8,8,8,8,8,8
23906365,14,14,14,14,14,14,14,14,14,14,14
23906411,8,8,8,8,8,8,8,8,8,8,8
23906438,7,7,7,7,7,7,7,7,7,7,7
23906439,7,7,7,7,7,7,7,7,7,7,7
23936691,7,7,7,7,7,7,7,7,7,7,7
23936700,7,7,7,7,7,7,7,7,7,7,7
24373888,15,15,15,15,0,15,15,15,15,15,15
24373889,13,13,13,13,0,13,13,13,13,13,13
24379567,8,8,8,8,0,8,8,8,8,8,8
24379568,8,8,8,8,0,8,8,8,8,8,8
24379569,14,14,14,14,0,14,14,14,14,14,14
24379571,6,6,6,6,0,6,6,6,6,6,6
24379574,13,13,13,13,0,13,13,13,13,13,13
24379575,11,11,11,11,0,11,11,11,11,11,11
24382656,15,15,15,15,0,15,15,15,15,15,15
24488627,7,7,7,7,7,7,7,7,7,7,7
24488629,7,7,7,7,7,7,7,7,7,7,7
24491133,14,14,14,14,0,14,14,14,14,14,14
24574008,12,12,12,12,12,12,12,12,12,12,12
24574257,7,7,7,7,7,7,7,7,7,7,7
24574258,8,8,8,8,8,8,8,8,8,8,8
24574995,4,4,4,4,4,4,4,4,4,4,4
24575089,6,6,6,6,0,6,6,6,6,6,6
24575496,14,14,14,14,14,14,14,14,14,14,14
24575590,8,8,8,8,8,8,8,8,8,8,8
24575611,6,6,6,6,0,6,6,6,6,6,6
24782657,8,8,8,8,8,8,8,8,8,8,8
24782658,7,7,7,7,7,7,7,7,7,7,7

In [48]:
result[result['article_no']==24382656]

,name,brand,gender,category,size,price,composition,color,url,img_url,article_no,blob_url
2994,LÄDERSNEAKERS - Finns i fler färger,zara,boy,SKOR,NaN,"359,00 SEK",100% BOVINE LE,Senapsgul,https://www.zara.com/se/sv/l%C3%A4dersneakers-p15435003.html,https://static.zara.net/photos///2019/I/1/3/p/5435/003/124/2/w/560/5435003124_1_1_1.jpg?ts=1563302681407,24382656,https://storage.googleapis.com/urbankiddo/zara/24382656
2995,LÄDERSNEAKERS - Finns i fler färger,zara,boy,SKOR,NaN,"359,00 SEK",100% BOVINE LE,Senapsgul,https://www.zara.com/se/sv/l%C3%A4dersneakers-p15435003.html,https://static.zara.net/photos///2019/I/1/3/p/5435/003/124/2/w/560/5435003124_1_1_1.jpg?ts=1563302681407,24382656,https://storage.googleapis.com/urbankiddo/zara/24382656
2996,LÄDERSNEAKERS - Finns i fler färger,zara,boy,SKOR,NaN,"359,00 SEK",100% BOVINE LE,Senapsgul,https://www.zara.com/se/sv/l%C3%A4dersneakers-p15435003.html,https://static.zara.net/photos///2019/I/1/3/p/5435/003/124/2/w/560/5435003124_1_1_1.jpg?ts=1563302681407,24382656,https://storage.googleapis.com/urbankiddo/zara/24382656
2997,LÄDERSNEAKERS - Finns i fler färger,zara,boy,SKOR,NaN,"359,00 SEK",100% BOVINE LE,Senapsgul,https://www.zara.com/se/sv/l%C3%A4dersneakers-p15435003.html,https://static.zara.net/photos///2019/I/1/3/p/5435/003/124/2/w/560/5435003124_1_1_1.jpg?ts=1563302681407,24382656,https://storage.googleapis.com/urbankiddo/zara/24382656
2998,LÄDERSNEAKERS - Finns i fler färger,zara,boy,SKOR,NaN,"359,00 SEK",100% BOVINE LE,Senapsgul,https://www.zara.com/se/sv/l%C3%A4dersneakers-p15435003.html,https://static.zara.net/photos///2019/I/1/3/p/5435/003/124/2/w/560/5435003124_1_1_1.jpg?ts=1563302681407,24382656,https://storage.googleapis.com/urbankiddo/zara/24382656
2999,LÄDERSNEAKERS - Finns i fler färger,zara,boy,SKOR,NaN,"359,00 SEK",100% BOVINE LE,Senapsgul,https://www.zara.com/se/sv/l%C3%A4dersneakers-p15435003.html,https://static.zara.net/photos///2019/I/1/3/p/5435/003/124/2/w/560/5435003124_1_1_1.jpg?ts=1563302681407,24382656,https://storage.googleapis.com/urbankiddo/zara/24382656
3000,LÄDERSNEAKERS - Finns i fler färger,zara,boy,SKOR,NaN,"359,00 SEK",100% BOVINE LE,Senapsgul,https://www.zara.com/se/sv/l%C3%A4dersneakers-p15435003.html,https://static.zara.net/photos///2019/I/1/3/p/5435/003/124/2/w/560/5435003124_1_1_1.jpg?ts=1563302681407,24382656,https://storage.googleapis.com/urbankiddo/zara/24382656
3001,LÄDERSNEAKERS - Finns i fler färger,zara,boy,SKOR,NaN,"359,00 SEK",100% BOVINE LE,Senapsgul,https://www.zara.com/se/sv/l%C3%A4dersneakers-p15435003.html,https://static.zara.net/photos///2019/I/1/3/p/5435/003/124/2/w/560/5435003124_1_1_1.jpg?ts=1563302681407,24382656,https://storage.googleapis.com/urbankiddo/zara/24382656
3002,LÄDERSNEAKERS - Finns i fler färger,zara,boy,SKOR,NaN,"359,00 SEK",100% BOVINE LE,Senapsgul,https://www.zara.com/se/sv/l%C3%A4dersneakers-p15435003.html,https://static.zara.net/photos///2019/I/1/3/p/5435/003/124/2/w/560/5435003124_1_1_1.jpg?ts=1563302681407,24382656,https://storage.googleapis.com/urbankiddo/zara/24382656
3003,LÄDERSNEAKERS - Finns i fler färger,zara,boy,SKOR,NaN,"359,00 SEK",100% BOVINE LE,Senapsgul,https://www.zara.com/se/sv/l%C3%A4dersneakers-p15435003.html,https://static.zara.net/photos///2019/I/1/3/p/5435/003/124/2/w/560/5435003124_1_1_1.jpg?ts=1563302681407,24382656,https://storage.googleapis.com/urbankiddo/zara/24382656
3004,LÄDERSNEAKERS - Finns i fler färger,zara,boy,SKOR,NaN,"359,00 SEK",100% BOVINE LE,Senapsgul,https://www.zara.com/se/sv/l%C3%A4dersneakers-p15435003.html,https://static.zara.net/photos///2019/I/1/3/p/5435/003/124/2/w/560/5435003124_1_1_1.jpg?ts=1563302681407,24382656,https://storage.googleapis.com/urbankiddo/zara/24382656
3005,LÄDERSNEAKERS - Finns i fler färger,zara,boy,SKOR,NaN,"359,00 SEK",100% BOVINE LE,Senapsgul,https://www.zara.com/se/sv/l%C3%A4dersneakers-p15435003.html,https://static.zara.net/photos///2019/I/1/3/p/5435/003/124/2/w/560/5435003124_1_1_1.jpg?ts=1563302681407,24382656,https://storage.googleapis.com/urbankiddo/zara/24382656
3006,LÄDERSNEAKERS - Finns i fler färger,zara,boy,SKOR,NaN,"359,00 SEK",100% BOVINE LE,Senapsgul,https://www.zara.com/se/sv/l%C3%A4dersneakers-p15435003.html,https://static.zara.net/photos///2019/I/1/3/p/5435/003/124/2/w/560/5435003124_1_1_1.jpg?ts=1563302681407,24382656,https://storage.googleapis.com/urbankiddo/zara/24382656
3007,LÄDERSNEAKERS - Finns i fler färger,zara,boy,SKOR,NaN,"359,00 SEK",100% BOVINE LE,Senapsgul,https://www.zara.com/se/sv/l%C3%A4dersneakers-p15435003.html,https://static.zara.net/photos///2019/I/1/3/p/5435/003/124/2/w/560/5435003124_1_1_1.jpg?ts=1563302681407,24382656,https://storage.googleapis.com/urbankiddo/zara/24382656
3008,LÄDERSNEAKERS - Finns i fler färger,zara,boy,SKOR,NaN,"359,00 SEK",100% BOVINE LE,Senapsgul,https://www.zara.com/se/sv/l%C3%A4dersneakers-p15435003.html,https://static.zara.net/photos///2019/I/1/3/p/5435/003/124/2/w/560/5435003124_1_1_1.jpg?ts=1563302681407,24382656,https://storage.googleapis.com/urbankiddo/zara/24382656

In [12]:
result.drop_duplicates().count()

name           13101
brand          13101
gender         13101
category       13101
size           13101
price          13101
composition    13101
color          13101
url            13101
img_url        13101
article_no     13101
blob_url       13101
dtype: int64

In [13]:
result[result['gender']=='unisex'].drop_duplicates().count()

name           1456
brand          1456
gender         1456
category       1456
size           1456
price          1456
composition    1456
color          1456
url            1456
img_url        1456
article_no     1456
blob_url       1456
dtype: int64

In [14]:
len(result['name'].unique())

1271

In [15]:
len(result['price'].unique())

40

In [16]:
df = result.drop_duplicates()
df.count()

name           13101
brand          13101
gender         13101
category       13101
size           13101
price          13101
composition    13101
color          13101
url            13101
img_url        13101
article_no     13101
blob_url       13101
dtype: int64

In [17]:
df.groupby('article_no').count()

,name,brand,gender,category,size,price,composition,color,url,img_url,blob_url
article_no,,,,,,,,,,,
146706001,3,3,3,3,3,3,3,3,3,3,3
146706004,3,3,3,3,3,3,3,3,3,3,3
174057017,3,3,3,3,3,3,3,3,3,3,3
174057019,3,3,3,3,3,3,3,3,3,3,3
174057020,3,3,3,3,3,3,3,3,3,3,3
174057022,3,3,3,3,3,3,3,3,3,3,3
174057024,3,3,3,3,3,3,3,3,3,3,3
174057025,3,3,3,3,3,3,3,3,3,3,3
174057026,3,3,3,3,3,3,3,3,3,3,3
174057027,3,3,3,3,3,3,3,3,3,3,3
174057028,3,3,3,3,3,3,3,3,3,3,3
174057029,3,3,3,3,3,3,3,3,3,3,3
174057030,3,3,3,3,3,3,3,3,3,3,3
174057032,3,3,3,3,3,3,3,3,3,3,3
174057033,3,3,3,3,3,3,3,3,3,3,3
176550008,3,3,3,3,3,3,3,3,3,3,3
176550009,3,3,3,3,3,3,3,3,3,3,3
176550011,3,3,3,3,3,3,3,3,3,3,3
176550012,3,3,3,3,3,3,3,3,3,3,3
176550013,3,3,3,3,3,3,3,3,3,3,3
176550014,3,3,3,3,3,3,3,3,3,3,3
176550015,3,3,3,3,3,3,3,3,3,3,3
176550016,3,3,3,3,3,3,3,3,3,3,3
176550017,3,3,3,3,3,3,3,3,3,3,3
176550018,3,3,3,3,3,3,3,3,3,3,3
176550019,3,3,3,3,3,3,3,3,3,3,3
176550020,3,3,3,3,3,3,3,3,3,3,3
176550021,3,3,3,3,3,3,3,3,3,3,3
198518003,1,1,1,1,1,1,1,1,1,1,1
198518010,1,1,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...
805817001,1,1,1,1,1,1,1,1,1,1,1
805817002,1,1,1,1,1,1,1,1,1,1,1
805932001,1,1,1,1,1,1,1,1,1,1,1
805932002,1,1,1,1,1,1,1,1,1,1,1
805932003,1,1,1,1,1,1,1,1,1,1,1
806289001,3,3,3,3,3,3,3,3,3,3,3
806307001,3,3,3,3,3,3,3,3,3,3,3
806307002,3,3,3,3,3,3,3,3,3,3,3
806354001,1,1,1,1,1,1,1,1,1,1,1
808842001,2,2,2,2,2,2,2,2,2,2,2
808896001,1,1,1,1,1,1,1,1,1,1,1
809110001,2,2,2,2,2,2,2,2,2,2,2
810050001,1,1,1,1,1,1,1,1,1,1,1
811437001,2,2,2,2,2,2,2,2,2,2,2
811596001,2,2,2,2,2,2,2,2,2,2,2
811596002,2,2,2,2,2,2,2,2,2,2,2
813140001,1,1,1,1,1,1,1,1,1,1,1
813899001,1,1,1,1,1,1,1,1,1,1,1
815278003,1,1,1,1,1,1,1,1,1,1,1
815462001,1,1,1,1,1,1,1,1,1,1,1
815462002,1,1,1,1,1,1,1,1,1,1,1
815745001,1,1,1,1,1,1,1,1,1,1,1
815791001,1,1,1,1,1,1,1,1,1,1,1
819036001,1,1,1,1,1,1,1,1,1,1,1
819036002,1,1,1,1,1,1,1,1,1,1,1
819519001,1,1,1,1,1,1,1,1,1,1,1
819519002,1,1,1,1,1,1,1,1,1,1,1
821013001,1,1,1,1,1,1,1,1,1,1,1
822443001,1,1,1,1,1,1,1,1,1,1,1
822653001,1,1,1,1,1,1,1,1,1,1,1

In [18]:
df[df['article_no']==811596002]

,name,brand,gender,category,size,price,composition,color,url,img_url,article_no,blob_url
1693,2-pack leggings,H&M,unisex,leggings,50-74,"129,00 kr.","Bomull 95%, Elastan 5%",Mörk dimrosa/Blommig,https://www2.hm.com/sv_se/productpage.08115960...,https://lp2.hm.com/hmgoepprod?set=source[/9d/1...,811596002,https://storage.googleapis.com/urbankiddo/H%26...
1881,2-pack leggings,H&M,girl,leggings,68-104,"129,00 kr.","Bomull 95%, Elastan 5%",Mörk dimrosa/Blommig,https://www2.hm.com/sv_se/productpage.08115960...,https://lp2.hm.com/hmgoepprod?set=source[/9d/1...,811596002,https://storage.googleapis.com/urbankiddo/H%26...

## same article number because of unisex both male and female also note sizes

In [19]:
df[df['article_no']==146706001]

,name,brand,gender,category,size,price,composition,color,url,img_url,article_no,blob_url
86,3-pack body,H&M,unisex,babybody,50-74,"89,90 kr.",Bomull 100%,Vit,https://www2.hm.com/sv_se/productpage.01467060...,https://lp2.hm.com/hmgoepprod?set=source[/9d/4...,146706001,https://storage.googleapis.com/urbankiddo/H%26...
26,3-pack body,H&M,boy,babybody,68-104,"89,90 kr.",Bomull 100%,Vit,https://www2.hm.com/sv_se/productpage.01467060...,https://lp2.hm.com/hmgoepprod?set=source[/9d/4...,146706001,https://storage.googleapis.com/urbankiddo/H%26...
39,3-pack body,H&M,girl,babybody,68-104,"89,90 kr.",Bomull 100%,Vit,https://www2.hm.com/sv_se/productpage.01467060...,https://lp2.hm.com/hmgoepprod?set=source[/9d/4...,146706001,https://storage.googleapis.com/urbankiddo/H%26...

In [20]:
pd.set_option('display.max_colwidth', -1) #full colunm dispaly
df[df['article_no']==146706001]['url']

86    https://www2.hm.com/sv_se/productpage.0146706001.html
26    https://www2.hm.com/sv_se/productpage.0146706001.html
39    https://www2.hm.com/sv_se/productpage.0146706001.html
Name: url, dtype: object

In [21]:
df2=df[df['article_no']==146706001]
df2.head()

,name,brand,gender,category,size,price,composition,color,url,img_url,article_no,blob_url
86,3-pack body,H&M,unisex,babybody,50-74,"89,90 kr.",Bomull 100%,Vit,https://www2.hm.com/sv_se/productpage.0146706001.html,"https://lp2.hm.com/hmgoepprod?set=source[/9d/47/9d477700382320194173b3e400db650e7cc3dcdd.jpg],origin[dam],category[kids_babyboy_bodies],type[DESCRIPTIVESTILLLIFE],hmver[1]&call=url[file:/product/main]+",146706001,https://storage.googleapis.com/urbankiddo/H%26M/0146706001
26,3-pack body,H&M,boy,babybody,68-104,"89,90 kr.",Bomull 100%,Vit,https://www2.hm.com/sv_se/productpage.0146706001.html,"https://lp2.hm.com/hmgoepprod?set=source[/9d/47/9d477700382320194173b3e400db650e7cc3dcdd.jpg],origin[dam],category[kids_babyboy_bodies],type[DESCRIPTIVESTILLLIFE],hmver[1]&call=url[file:/product/main]+",146706001,https://storage.googleapis.com/urbankiddo/H%26M/0146706001
39,3-pack body,H&M,girl,babybody,68-104,"89,90 kr.",Bomull 100%,Vit,https://www2.hm.com/sv_se/productpage.0146706001.html,"https://lp2.hm.com/hmgoepprod?set=source[/9d/47/9d477700382320194173b3e400db650e7cc3dcdd.jpg],origin[dam],category[kids_babyboy_bodies],type[DESCRIPTIVESTILLLIFE],hmver[1]&call=url[file:/product/main]+",146706001,https://storage.googleapis.com/urbankiddo/H%26M/0146706001

In [22]:
df2 = df2.drop_duplicates(['article_no'])
df2.head()

,name,brand,gender,category,size,price,composition,color,url,img_url,article_no,blob_url
86,3-pack body,H&M,unisex,babybody,50-74,"89,90 kr.",Bomull 100%,Vit,https://www2.hm.com/sv_se/productpage.0146706001.html,"https://lp2.hm.com/hmgoepprod?set=source[/9d/47/9d477700382320194173b3e400db650e7cc3dcdd.jpg],origin[dam],category[kids_babyboy_bodies],type[DESCRIPTIVESTILLLIFE],hmver[1]&call=url[file:/product/main]+",146706001,https://storage.googleapis.com/urbankiddo/H%26M/0146706001

In [23]:
df.count()

name           13101
brand          13101
gender         13101
category       13101
size           13101
price          13101
composition    13101
color          13101
url            13101
img_url        13101
article_no     13101
blob_url       13101
dtype: int64

In [26]:
df.to_csv('H&M.csv',index=False) #for rows not showing